### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Camilochiang** [hereariim/napari-blossom#1]
Great plugin. Do you have a publiocation for the dataset? same with napari-apple

**Comment by hereariim** [comment]
In order to make inferences, the images were not published. For napari-blossom, the image type is 
![IMG_3330](https://user-images.githubusercontent.com/93375163/207255013-f15924ab-6e07-4008-a790-6bbd69153332.jpg)

**Comment by hereariim** [comment]
For napari-apple, you can use images of apples taken in a field. A picture of an apple tree.

**Comment by Camilochiang** [comment]
Could you share the images that were used for training? It will be nice if  it is possible! Thanks

**Comment by hereariim** [comment]
Hi @Camilochiang 
The training data was acquired as part of a project. This project makes the data private. Unfortunately, I cannot share this data publicly.
