### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by goanpeca** [hereariim/napari-blossom#2]
Hi @hereariim 

While working on https://github.com/conda-forge/napari-blossom-feedstock/pull/5 

I noticed `python_requires = ==3.8`, is there a reason for that strict pinning?

https://github.com/hereariim/napari-blossom/blob/main/setup.cfg#L45

Cheers!

**Comment by hereariim** [comment]
Hi @goanpeca 

Initially, there is no reason. 
I can't get my module to work from built-in napari. In doing so, I thought that the tensorflow package would work, and by transitivity, the module would work. Unfortunately, it didn't. You can remove it if you think it's unnecessary.

Best!

**Comment by goanpeca** [comment]
@hereariim I will need to add a patch tio be able to build the recipe, otherwise it wont work. Could you add. please change this to `python_requires = >=3.8` ?

Cheers

**Comment by goanpeca** [comment]
@hereariim it also seems all your dependencies are hard pins. That can generate issues when solving environments

```
install_requires =
    numpy==1.23.0
    magicgui==0.6.1
    qtpy
    opencv-python-headless==4.7.0.68
    tensorflow==2.11.0
    scikit-image==0.19.3
    napari
    focal_loss==0.0.7
    pillow==9.3.0
    tqdm==4.64.1

```

Please try to use >= or <=, and not ==

**Comment by hereariim** [comment]
thanks, i added modifications,
best,

**Comment by hereariim** [comment]
@goanpeca thanks, i added modifications,
best,
