### ISSUE TITLE
Please delete setup.py

### ISSUE THREAD

**Issue by goanpeca** [hereariim/napari-blossom#3]
Hi @hereariim, while working on https://github.com/conda-forge/dclab-feedstock/pull/14

We noticed that you are using `setup.cfg`, and `setup.py`, please delete `setup.py` and only use pyproject.toml and setup.cfg to configure the package.

Could you fix this for the next release?

Cheers 🚀 !

**Comment by hereariim** [comment]
ok, i just deleted

**Comment by hereariim** [comment]
ok, i just deleted @goanpeca
